package vehicle

import "context"

// Repository defines the persistence operations required by the vehicle
// service. It is implemented by PostgresRepository for production use and
// can be faked in tests.
type Repository interface {
	// CategoryStatus reports whether a vehicle category with the given ID
	// exists and, if so, whether it is active. found is false when no
	// non-deleted category with that ID exists.
	CategoryStatus(ctx context.Context, categoryID string) (found bool, active bool, err error)

	// CreateVehicle persists a new vehicle record and returns the fields
	// generated by the database (ID, timestamps). It returns
	// ErrDuplicateVIN or ErrDuplicatePlateNumber if a uniqueness constraint
	// is violated.
	CreateVehicle(ctx context.Context, v *Vehicle) error
}
